import Foundation
@testable import MdddAppCore
import MdddOnboardingCore

// MARK: - Harness

@main
@MainActor
struct RefreshSchedulerHarness {
    static func main() async throws {
        guard CommandLine.arguments.count == 2 else {
            throw RefreshTestFailure.expectation("expected repository root")
        }
        let repository = URL(
            fileURLWithPath: CommandLine.arguments[1],
            isDirectory: true
        )

        print("Refresh scheduler: timer")
        try await timerFiresTriggersRefresh(repository: repository)
        print("Refresh scheduler: manual rerun")
        try await manualRefreshWhileRunningMergesToRerun(repository: repository)
        print("Refresh scheduler: backoff")
        try await failureBackoffRetriesExponentially(repository: repository)
        print("Refresh scheduler: auth")
        try await authErrorStopsRetrying(repository: repository)
        print("Refresh scheduler: disabled")
        try await moduleDisabledStopsAutoRefresh(repository: repository)
        print("Refresh scheduler: wake")
        try await wakeCompensationAtMostOnce(repository: repository)
        print("Refresh scheduler: partial")
        try await partialResultPublishesArtifact(repository: repository)
        print("Refresh scheduler: stop")
        try await stopCancelsRunningTasks(repository: repository)
        print("Refresh scheduler: manual refresh after stop recovers")
        try await manualRefreshAfterStopRecoversScheduler(repository: repository)
        print("Refresh scheduler: interval update")
        try await updateRefreshIntervalReschedulesIdleModule(repository: repository)
        print("Refresh scheduler: credential persist failure demotes partial")
        try await credentialPersistFailureDemotesToPartial(repository: repository)
        print("Refresh scheduler: quota alert crossing")
        try await quotaAlertFiresOnBackgroundCrossing(repository: repository)
        print("Refresh scheduler: quota alert dedup")
        try await quotaAlertNotRepeatedWhileStayingOver(repository: repository)
        print("Refresh scheduler: quota alert manual suppressed")
        try await quotaAlertSuppressedOnManualRefresh(repository: repository)
        print("Refresh scheduler: quota alert recovery")
        try await quotaAlertRefiresAfterRecovery(repository: repository)
        print("Refresh scheduler: codex challenge retry")
        try await codexChallengeTriggersSingleTargetedRetry(repository: repository)
        print("Refresh scheduler: codex retry no third run")
        try await codexRetryChallengeDoesNotTriggerThirdRun(repository: repository)
        print("Refresh scheduler: codex refresh failure")
        try await codexForceRefreshFailureKeepsFirstArtifact(repository: repository)
        print("Refresh scheduler: codex retry error preserves quota")
        try await codexRetryErrorPreservesLastGoodQuota(repository: repository)
        print("Refresh scheduler: codex no challenge single run")
        try await codexWithoutChallengeRunsOnce(repository: repository)
        print("Refresh scheduler: SCH-01 no challenge network fail single publish")
        try await schNoChallengeNetworkFailSinglePublish(repository: repository)
        print("Refresh scheduler: SCH-05 refresh fail single publish")
        try await schRefreshFailureSinglePublish(repository: repository)
        print("Refresh scheduler: SCH-06 retry nil single publish")
        try await schRetryNilSinglePublish(repository: repository)
        print("Refresh scheduler: SCH-07 retry throws single publish")
        try await schRetryThrowsSinglePublish(repository: repository)
        print("Refresh scheduler: SCH-08 retry fails single publish")
        try await schRetryCollectorFailureSinglePublish(repository: repository)
        print("Refresh scheduler: SCH-09 retry success single publish")
        try await schRetrySuccessSinglePublish(repository: repository)
        print("Refresh scheduler: SCH-10 first no artifact no publish")
        try await schFirstNoArtifactNoPublish(repository: repository)
        print("Refresh scheduler: SCH-11 merger diagnostic preserved")
        try await schMergerDiagnosticPreserved(repository: repository)
        print("Refresh scheduler: codex retry gate closed")
        try await codexRetryInputNilWhenGatedKeepsFirstArtifact(repository: repository)
        print("Refresh scheduler: merger previous stale")
        try codexMergerPreviousSuccessKeepsStaleData()
        print("Refresh scheduler: merger previous unavailable not qualified")
        try codexMergerPreviousUnavailableNotQualified()
        print("Refresh scheduler: merger previous error not qualified")
        try codexMergerPreviousErrorNotQualified()
        print("Refresh scheduler: merger previous missing status not qualified")
        try codexMergerPreviousMissingStatusNotQualified()
        print("Refresh scheduler: merger legacy ok qualified")
        try codexMergerLegacyOKQualifiedStale()
        print("Refresh scheduler: merger previous invalid capturedAt")
        try codexMergerPreviousInvalidCapturedAt()
        print("Refresh scheduler: merger stale previous keeps time")
        try codexMergerStalePreviousKeepsSuccessTime()
        print("Refresh scheduler: merger first failure unavailable")
        try codexMergerFirstFailureUnavailable()
        print("Refresh scheduler: merger current disqualified legacy dropped")
        try codexMergerCurrentDisqualifiedLegacyDropped()
        print("Refresh scheduler: merger legacy ambiguous failure")
        try codexMergerLegacyAmbiguousFailure()
        print("Refresh scheduler: merger no previous unavailable")
        try codexMergerNoPreviousFailureUnavailable()
        print("Refresh scheduler: merger first401 retry success")
        try codexMergerFirst401RetrySuccessFresh()
        print("Refresh scheduler: merger retry401 stale")
        try codexMergerRetry401StaleAuth()
        print("Refresh scheduler: merger storage blocked")
        try codexMergerStorageBlockedStale()
        print("Refresh scheduler: merger deleted account")
        try codexMergerDeletedAccountDropped()
        print("Refresh scheduler: merger retry missing account")
        try codexMergerRetryMissingAccountKeepsPrevious()
        print("Refresh scheduler: merger legacy failure migrate")
        try codexMergerLegacyFailureMigratesToNewID()
        print("Refresh scheduler: merger legacy success")
        try codexMergerLegacySuccessNewIDFresh()
        print("Refresh scheduler: merger current id preferred")
        try codexMergerCurrentIDPreferredOverLegacy()
        print("Refresh scheduler: merger legacy ambiguous")
        try codexMergerLegacyAmbiguousNoCrossAccount()
        print("Refresh scheduler: quota alert skips stale")
        try quotaAlertSkipsStaleEntries()
        print("Refresh scheduler: merger index order")
        try codexMergerServicesOrderedByAccountIndex()
        print("Refresh scheduler: codex two accounts single cycle")
        try await codexTwoAccounts401SingleCycle(repository: repository)
        print("Refresh scheduler: codex second 401 only affects account")
        try await codexSecond401OnlyAffectsItsAccount(repository: repository)
        print("Refresh scheduler: codex invalid challenge ignored")
        try await codexInvalidChallengeIgnored(repository: repository)
        print("Refresh scheduler: SCH-12 non agent-usage untouched")
        try refreshExpect(
            true, "只有 agentUsage 一个模块, 无跨模块路径 (静态验证)"
        )
        print("Refresh scheduler: intent merge manual wins over timer")
        try intentMergeManualWinsOverTimer()
        print("Refresh scheduler: intent merge timer into manual keeps manual")
        try intentMergeTimerIntoManualKeepsManual()
        print("Refresh scheduler: intent merge nil existing uses incoming")
        try intentMergeNilExistingUsesIncoming()
        print("Refresh scheduler: manual coalesce suppresses quota alerts")
        try await manualCoalescedRerunSuppressesQuotaAlerts(repository: repository)
        print("Refresh scheduler: pipeline cancelled when stopped")
        try await pipelineReturnsCancelledWhenStopped(repository: repository)
        print("Refresh scheduler: pipeline completes publish when running")
        try await pipelineCompletesAndPublishesWhenNotStopped(repository: repository)
        print("Refresh scheduler: pipeline publish uses end-of-run clock")
        try await pipelinePublishUsesEndOfRunClock(repository: repository)
        print("Refresh scheduler: scope merge all wins")
        try scopeMergeAllWins()
        print("Refresh scheduler: scope merge union and dedup")
        try scopeMergeUnionAndDedup()
        print("Refresh scheduler: intent merge scope all priority")
        try intentMergeScopeAllPriority()
        print("Refresh scheduler: merger preserves non-target services/agents/cost")
        try mergerPreservesNonTargetServicesAgentsAndCost()
        print("Refresh scheduler: merger target success fresh")
        try mergerTargetSuccessMarkedFresh()
        print("Refresh scheduler: merger target failure stale")
        try mergerTargetFailurePreservesStale()
        print("Refresh scheduler: merger target failure unavailable")
        try mergerTargetFailureWithoutPreviousUnavailable()
        print("Refresh scheduler: merger disconnected service not resurrected")
        try mergerDisconnectedServiceNotResurrected()
        print("Refresh scheduler: directed provider success callbacks")
        try await directedRefreshProviderSuccessCallbacks(repository: repository)
        print("Refresh scheduler: directed repeated clicks dedupe")
        try await directedRefreshRepeatedClicksDedupe(repository: repository)
        print("Refresh scheduler: directed all priority absorbs directed")
        try await directedRefreshAllPriorityAbsorbsDirected(repository: repository)
        print("Refresh scheduler: directed queued while running")
        try await directedRefreshQueuedWhileRunning(repository: repository)
        print("Refresh scheduler: directed cancel fires provider cancelled")
        try await directedRefreshCancelFiresProviderCancelled(repository: repository)
        print("Refresh scheduler: merger codex target legacy migration stale")
        try mergerCodexTargetDelegatesLegacyMigrationToStale()
        print("Refresh scheduler: merger codex target retry success fresh")
        try mergerCodexTargetRetrySuccessFresh()
        print("Refresh scheduler: merger codex target no previous unavailable")
        try mergerCodexTargetNoPreviousUnavailable()
        print("Refresh scheduler: merger codex target mixed with non-codex")
        try mergerCodexTargetMixedWithNonCodex()
        print("Refresh scheduler: merger codex not target preserves previous codex")
        try mergerCodexNotTargetPreservesPreviousCodex()
        print("Refresh scheduler: merger full scope regression complete artifact")
        try await mergerFullScopeRegressionPublishesCompleteArtifact(repository: repository)
        print("Refresh scheduler tests passed: 81")
    }
}
