import Foundation
@testable import MdddOnboardingCore

// MARK: - 非交互环境守卫

/// 无头 CI runner 无登录会话: 真实 Keychain 读写触发系统授权等待会挂起.
/// 检测 GitHub Actions (`CI=true`) 或进程无代码签名且非 TTY.
enum IsNonInteractiveEnvironment {
    static var runningInCI: Bool {
        let env = ProcessInfo.processInfo.environment
        if env["CI"] != nil && env["CI"] != "" {
            return true
        }
        // 本地终端无签名进程仍走真实 Keychain (登录会话可授权);
        // 仅无 CI 标记时放行, 保守只认 CI 变量, 避免误跳过本地测试.
        return false
    }
}

// MARK: - Harness

@main
@MainActor
struct MdddOnboardingCoreHarness {
    static func main() async throws {
        try pythonVersionParses_3_9()
        try pythonVersionParses_3_12()
        try pythonVersionParsesWithWhitespace()
        try pythonVersionParsesMissingPatch()
        try pythonVersionRejects_2_7()
        try pythonVersionRejects_3_8()
        try pythonVersionRejectsGarbage()
        try pythonPathResolvesUserPreferred()
        try pythonPathFallsBackToCandidates()
        try pythonPathReturnsNilWhenNoneFound()
        try gateDeniesAllBeforeConsent()
        try gateDeniesWhenConsentVersionMismatch()
        try gateAllowsAgentReady()
        try gateAllowsAgentPartial()
        try gateDeniesUnselectedModule()
        try gateDeniesWhenAppNotAcceptingTasks()
        try gateDeniesPendingAuthorization()
        try gateDeniesNetworkUnreachable()
        try agentPolicyOnlyLocalCapabilities()
        try policyNilWhenNotReady()
        try evaluatorAgentReady()
        try evaluatorAgentPartial()
        try evaluatorAgentMissingPython()
        try evaluatorAgentNoSessions()
        try evaluatorAgentCcSwitchAloneNotReady()
        try configStoreRoundTrip()
        try configStoreReturnsEmptyWhenMissing()
        try configStoreReturnsNilForUnknownSchema()
        try configStoreFilePermissions()
        try credentialStoreRoundTrip()
        try credentialStoreDelete()
        try credentialStoreIsolatesByAccount()
        try gateEvaluatorDeniesAllBeforeConsent()
        try gateEvaluatorEnablesOnlyReadyAndSelected()
        try ccSwitchProfileHasExpectedTables()
        try antigravityProfileHasExpectedTables()
        try await probeSuccessCapturesOutput()
        try await probeLaunchFailedForMissingExecutable()
        try await probeNonZeroExitCapturesStderrSummary()
        try await probeTimeoutForceKillsIgnoringSIGTERM()
        try await probeCallerCancellationTerminatesProcess()
        try await probeOutputCapTruncatesAndDrains()
        try await sqliteProbeAvailableForValidSchema()
        try await sqliteProbeMissingPath()
        try await sqliteProbeIncompatibleWhenMissingTable()
        try await sqliteProbeIncompatibleWhenMissingColumn()
        try await sqliteProbeRejectsSubstringColumnTrap()
        try await sqliteProbeCorruptedForGarbageFile()
        try sqliteLockedDetectionUsesStderr()
        try sqliteTableInfoParsesColumnNames()
        // 真实 Keychain 测试仅在交互环境运行: 无头 CI runner 无登录会话,
        // SecItem* 触发系统授权等待会挂起至超时 (本地已有登录会话, 自动通过).
        if !IsNonInteractiveEnvironment.runningInCI {
            try keychainUpdatePreservesAndOverwrites()
        }
        try await scannerFindsPythonSessionsAndSQLite()
        try await scannerReportsMissingPython()
        try standardPathsIncludePiSessions()
        try standardPathsIncludeZcodeDatabase()
        try firstLaunchDecisionFlow()
        try configStoreLoadsV1WithSubscriptionDefaults()
        try configStoreRejectsNewerSchemaV3()
        try configStoreSubscriptionProvidersRoundTrip()
        try configRefreshIntervalDecodeAndFallback()
        try credentialStoreSubscriptionAccountsRoundTrip()
        if !IsNonInteractiveEnvironment.runningInCI {
            try keychainSubscriptionAccountsRoundTrip()
        }
        try await verifierDeepSeekConnectedWithMockSession()
        try await verifierDeepSeekFailClosed()
        try verifierKimiAPIKeyMappings()
        try verifierCodexAccountsJSONMappings()
        try verifierAntigravityOAuthJSONMappings()
        try verifierVolcengineCredentialsMappings()
        try verifierZhipuCredentialsMappings()
        try gateAgentPolicyGrantsExternalQuotasWhenConfigured()
        try gateEvaluatorPropagatesSubscriptionFlag()
        try volcDecoderStopsWhenNotBase64()
        try volcDecoderSingleAndDoubleEncoded()
        try volcFullyDecodedPicksDeepestCandidate()
        try codexAuthFileParsesValidAccount()
        try codexAuthFileRejectsMissingFields()
        try codexLibraryMergingCreatesPreservesUpdates()
        try codexLibrarySummaryCountAndPrefixes()
        try codexChooseActiveAccountPriority()
        try await ccSwitchVolcImportReadsFixtureDatabase()
        try await ccSwitchVolcImportMissingProviderRow()
        try await ccSwitchVolcImportMissingFile()
        try subscriptionConfigApplyingVerificationTransitions()
        try subscriptionUsageTrackingIDDecodeAndFallback()
        try applyingVerificationPreservesUsageTrackingID()
        try deepSeekSaveTransactionPrewriteDisabled()
        try deepSeekSaveTransactionRestoreOldEntry()
        try deepSeekSaveTransactionRestoreRemovesWhenAbsent()
        try deepSeekSaveTransactionIsolatesEachSave()
        try await probeStandardInputPipesToProcess()
        try codexPKCEVerifierFormat()
        try codexDeviceStartRequestAndParse()
        try codexDevicePollAndExchangeParsing()
        try codexIDTokenClaimsParsing()
        try await codexDeviceFullFlowStoresAccount()
        try await codexDeviceErrorPaths()
        try await codexDeviceExpiredSkipsPolling()
        try await codexDeviceFlowPreservesExpiresIn()
        try codexExpiryPriorityExpiresInOverJWTAndFallback()
        try rotationMergeMapsKnownProviders()
        try rotationMergeKimiRejected()
        try rotationMergeCodexRejected()
        try rotationMergeAntigravityTokenSubObject()
        try rotationMergeFiltersKeysAndRejectsUnknown()
        try CodexCredentialStoreTests.runAll()
        try await CodexOAuthClientTests.runAll()
        try CredentialStateReducerTests.runAll()
        try await CodexTokenManagerTests.runAll()
        try await codexLoginStoresCompleteV2Record()
        try await ccSwitchDiscoveryKeepsMetadataOnly()
        try cliDiscoveryKeepsMetadataOnly()
        try await discoveryNeverWritesSourceFiles()
        try await reauthorizationReplacesOnlyCurrentAccount()
        try await disconnectRemovesRecordButKeepsOthers()
        try configAppearanceModeDecodeAndFallback()
        try configGlassStyleDecodeAndFallback()
        try codexAccountIdentityServiceIDMatchesPython()
        try codexAccountIdentityLegacyID()
        try evaluatorGrokExpiredReturnsExpired()
        try evaluatorGrokValidOIDCPreferredOverLegacy()
        try evaluatorGrokMillisTimestamp()
        try evaluatorGrokISOString()
        try evaluatorGrokMissingKeyAndCorrupt()
        try evaluatorClaudeExpiredAndLegacyKey()
        try evaluatorClaudeMissingToken()
        try evaluatorKimiAPIKey()
        try evaluatorAntigravityRefreshMissing()
        try evaluatorIsExpiredSemanticsMatchPython()
        try evaluatorSharedExpiryFixtures()
        try claudePasteParserTokenAndJSON()
        try claudePasteParserRejectsEmpty()
        try grokPasteParserTokenAndJSON()
        try grokPasteParserRejectsEmpty()
        try claudeCLIImporterReadsFixture()
        try grokCLIImporterReadsFixture()
        try claudeGrokCredentialAccountsReturnNewKeys()
        try configSubscriptionProviderOrderRoundTrip()
        try configuredRuleAllAccountsNonEmpty()
        try configuredRuleCodexRecords()
        try configuredRuleClaudeAppPrefersOverLocal()
        try configuredRuleClaudeFallsBackToLocal()
        try configuredRuleClaudeExpiredAppFallsBackToLocal()
        try configuredRuleGrokAppPrefersOverLocal()
        try configuredRuleGrokFallsBackToLocal()
        try configuredRuleGrokExpiredAppFallsBackToLocal()
        try configuredRuleRegistryMatchesProviders()
        try opencodeGoCredentialAccountsAndRegistry()
        try opencodeGoEvaluatorValidAndMalformed()
        try opencodeGoAccountIDAndLegacyKeys()
        print("MdddOnboardingCore tests passed: 177")
    }
}
